/** @type {import('tailwindcss').Config} */
const withVar = (name, fallback) => `var(${name}, ${fallback})`

export default {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        brand: {
          navy: {
            50: withVar("--brand-navy-50", "#f0f4ff"),
            100: withVar("--brand-navy-100", "#e0e7ff"),
            200: withVar("--brand-navy-200", "#c7d2fe"),
            300: withVar("--brand-navy-300", "#a5b4fc"),
            400: withVar("--brand-navy-400", "#818cf8"),
            500: withVar("--brand-navy-500", "#6366f1"),
            600: withVar("--brand-navy-600", "#4f46e5"),
            700: withVar("--brand-navy-700", "#1e3a8a"),
            800: withVar("--brand-navy-800", "#1e3a8a"),
            900: withVar("--brand-navy-900", "#1e293b"),
          },
          carbon: {
            50: withVar("--brand-carbon-50", "#f9fafb"),
            100: withVar("--brand-carbon-100", "#f3f4f6"),
            200: withVar("--brand-carbon-200", "#e5e7eb"),
            300: withVar("--brand-carbon-300", "#d1d5db"),
            400: withVar("--brand-carbon-400", "#9ca3af"),
            500: withVar("--brand-carbon-500", "#6b7280"),
            600: withVar("--brand-carbon-600", "#4b5563"),
            700: withVar("--brand-carbon-700", "#374151"),
            800: withVar("--brand-carbon-800", "#1f2937"),
            900: withVar("--brand-carbon-900", "#111827"),
          },
          royal: {
            50: withVar("--brand-royal-50", "#eff6ff"),
            100: withVar("--brand-royal-100", "#dbeafe"),
            200: withVar("--brand-royal-200", "#bfdbfe"),
            300: withVar("--brand-royal-300", "#93c5fd"),
            400: withVar("--brand-royal-400", "#60a5fa"),
            500: withVar("--brand-royal-500", "#3b82f6"),
            600: withVar("--brand-royal-600", "#2563eb"),
            700: withVar("--brand-royal-700", "#1d4ed8"),
            800: withVar("--brand-royal-800", "#1e40af"),
            900: withVar("--brand-royal-900", "#1e3a8a"),
          },
          gold: {
            50: withVar("--brand-gold-50", "#fffbeb"),
            100: withVar("--brand-gold-100", "#fef3c7"),
            200: withVar("--brand-gold-200", "#fde68a"),
            300: withVar("--brand-gold-300", "#fcd34d"),
            400: withVar("--brand-gold-400", "#fbbf24"),
            500: withVar("--brand-gold-500", "#f59e0b"),
            600: withVar("--brand-gold-600", "#d97706"),
            700: withVar("--brand-gold-700", "#b45309"),
            800: withVar("--brand-gold-800", "#92400e"),
            900: withVar("--brand-gold-900", "#78350f"),
          },
          silver: {
            50: withVar("--brand-silver-50", "#f9fafb"),
            100: withVar("--brand-silver-100", "#f3f4f6"),
            200: withVar("--brand-silver-200", "#e5e7eb"),
            300: withVar("--brand-silver-300", "#d1d5db"),
            400: withVar("--brand-silver-400", "#9ca3af"),
            500: withVar("--brand-silver-500", "#6b7280"),
            600: withVar("--brand-silver-600", "#4b5563"),
            700: withVar("--brand-silver-700", "#374151"),
            800: withVar("--brand-silver-800", "#1f2937"),
            900: withVar("--brand-silver-900", "#111827"),
          },
        },
      },
    },
  },
  plugins: [],
}
